### ISSUE TITLE
interact with Airsim?

### ISSUE THREAD

**Issue by noahzn** [knmcguire/crazyflie_models#3]
Hi Kimberly,

Nice to hear you are working on crazyflie simulation. I am wondering if there's a plan of interaction with Airsim? I want to use Airsim to do some simulation of crazyflie. And do you know where can I find a mesh model of the crazyflie?

**Comment by knmcguire** [comment]
hi! no we don't have model for Airsim at the moment unfortunately. But it's good to keep in mind for the future

**Comment by noahzn** [comment]
How about the 3d model of Crazyflie? Does Bitcraze provide that?

**Comment by noahzn** [comment]
Do you have any updates? Thanks.

**Comment by knmcguire** [comment]
There are .dae mesh files in crazyflie folder which you can use if you want, but just mind that this is not yet really 'official', hence the reason that this is still on my personal github repo
