### ISSUE TITLE
trying to take off not working

### ISSUE THREAD

**Issue by eladpar-rnd** [knmcguire/crazyflie_models#4]
hey ive been trying to test the takeoff option im using ign fortress and ubuntu 20
and i get the following error:

`Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/body"]/inertial/pose[@frame=""]:crazyflie/model.sdf:L7]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/body"]/collision[@name="crazyflie/body_collision"]/pose[@frame=""]:crazyflie/model.sdf:L19]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/body"]/visual[@name="crazyflie/body_visual"]/pose[@frame=""]:crazyflie/model.sdf:L27]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m1_prop"]/pose[@frame=""]:crazyflie/model.sdf:L37]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m1_prop"]/inertial/pose[@frame=""]:crazyflie/model.sdf:L39]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m1_prop"]/visual[@name="crazyflie/m1_visual"]/pose[@frame=""]:crazyflie/model.sdf:L51]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m2_prop"]/pose[@frame=""]:crazyflie/model.sdf:L61]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m2_prop"]/inertial/pose[@frame=""]:crazyflie/model.sdf:L63]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m2_prop"]/visual[@name="crazyflie/m2_visual"]/pose[@frame=""]:crazyflie/model.sdf:L75]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m3_prop"]/pose[@frame=""]:crazyflie/model.sdf:L85]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m3_prop"]/inertial/pose[@frame=""]:crazyflie/model.sdf:L87]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m3_prop"]/visual[@name="crazyflie/m3_visual"]/pose[@frame=""]:crazyflie/model.sdf:L99]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m4_prop"]/pose[@frame=""]:crazyflie/model.sdf:L109]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m4_prop"]/inertial/pose[@frame=""]:crazyflie/model.sdf:L111]: XML Attribute[frame] in element[pose] not defined in SDF.
Warning [Utils.cc:129] [/sdf/model[@name="crazyflie"]/link[@name="crazyflie/m4_prop"]/visual[@name="crazyflie/m4_visual"]/pose[@frame=""]:crazyflie/model.sdf:L123]: XML Attribute[frame] in element[pose] not defined in SDF.
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen`

**Comment by knmcguire** [comment]
hi! which terminal command are you using? there are several options namely for take off

**Comment by eladpar-rnd** [comment]
Hi !
I'm using the command from the readme:
`ign gazebo crazyflieworld.sdf`
in addition the command 
`ign topic -t /crazyflie/gazebo/command/motor_speed --msgtype ignition.msgs.Actuators -p 'velocity:[2500,2500,2500,2500]'`
dosen't work, and there seems to be no crazyflie topic published :
`ign topic -l
/clock
/gazebo/resource_paths
/gui/camera/pose
/model/crazyflie/odometry
/stats
/world/empty/clock
/world/empty/dynamic_pose/info
/world/empty/pose/info
/world/empty/scene/deletion
/world/empty/scene/info
/world/empty/state
/world/empty/stats
`

**Comment by knmcguire** [comment]
Ah I know what is going on. The crazyflie model (crazyflie/model.sdf) still had the lee controller enabled and then apparently it is no long possible to control the motors individually. You will need to first comment out the multicopter control plugin in the model.sdf before it will react on those commands.

I've updated the README to better explain this.

**Comment by knmcguire** [comment]
Also, the warnings you see in the terminal for ignition gazebo, are no errors but only warnings that we are using outdated framework. But this doesnt indicate that there are problems with the model since you see them with regular flight as well... it's just a bit annoying to see it all the time :) so I'll look at that for another time.
